# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import oauth2_provider.generators
import oauth2_provider.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0004_auto_20160525_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials')], max_length=32, verbose_name='Authorization Grant Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True, verbose_name='Client id'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255, verbose_name='Client secret'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_type',
            field=models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32, verbose_name='Client type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed URIs list, space separated', validators=[oauth2_provider.validators.validate_uris], verbose_name='Redirect Uris'),
        ),
    ]
